{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Release.Name }}
data:
  config.json: {{ .Values.secret.config | b64enc  }}
{{- end -}}
