#!/usr/bin/env python3
"""
Prometheus metrics module for automerge token tracking.
"""

import logging
from typing import Optional

from prometheus_client import CollectorRegistry, Gauge, push_to_gateway

logger = logging.getLogger(__name__)


class AutomergeMetrics:
    """
    Class to handle Prometheus metrics for automerge token usage.
    """

    def __init__(self, pushgateway_url: Optional[str] = None, job_name: str = "automerge"):
        """
        Initialize metrics collector.
        Args:
            pushgateway_url: URL of the Prometheus Pushgateway
            job_name: Job name for the metrics
        """
        self.pushgateway_url = pushgateway_url
        self.job_name = job_name
        self.registry = CollectorRegistry()

        # Create gauge metrics for token usage
        self.input_tokens_gauge = Gauge(
            "automerge_input_tokens",
            "Number of input tokens used by AI analysis",
            ["repo", "model", "engine"],
            registry=self.registry
        )

        self.output_tokens_gauge = Gauge(
            "automerge_output_tokens",
            "Number of output tokens generated by AI analysis",
            ["repo", "model", "engine"],
            registry=self.registry
        )

        logger.info(f"Initialized AutomergeMetrics with pushgateway: {pushgateway_url}")

    def record_token_usage(self, repo: str, model: str, engine: str, input_tokens: int, output_tokens: int):
        """
        Record token usage metrics.
        Args:
            repo: Repository name
            model: AI model name (e.g., "claude-sonnet-4")
            engine: AI engine (e.g., "claude-code", "github-copilot")
            input_tokens: Number of input tokens used
            output_tokens: Number of output tokens generated
        """
        try:
            # Set the gauge values
            self.input_tokens_gauge.labels(
                repo=repo,
                model=model,
                engine=engine
            ).set(input_tokens)

            self.output_tokens_gauge.labels(
                repo=repo,
                model=model,
                engine=engine
            ).set(output_tokens)

            logger.debug(f"Recorded token usage - Repo: {repo}, Model: {model}, Engine: {engine}, "
                        f"Input: {input_tokens}, Output: {output_tokens}")

        except Exception as e:
            logger.error(f"Failed to record token usage metrics: {e}")

    def push_metrics(self):
        """
        Push metrics to Prometheus Pushgateway.
        """
        if not self.pushgateway_url:
            logger.debug("No pushgateway URL configured, skipping metrics push")
            return

        try:
            push_to_gateway(self.pushgateway_url, job=self.job_name, registry=self.registry)
            logger.info(f"Successfully pushed metrics to {self.pushgateway_url} (job={self.job_name})")
        except Exception as e:
            logger.error(f"Failed to push metrics to Pushgateway: {e}")

    def get_metrics_summary(self) -> dict:
        """
        Get a summary of current metrics values.
        Returns:
            Dictionary with metrics summary
        """
        summary = {
            "input_tokens": {},
            "output_tokens": {}
        }

        try:
            # Get input tokens metrics
            for metric in self.input_tokens_gauge.collect():
                for sample in metric.samples:
                    labels = sample.labels
                    key = f"{labels['repo']}_{labels['model']}_{labels['engine']}"
                    summary["input_tokens"][key] = sample.value

            # Get output tokens metrics
            for metric in self.output_tokens_gauge.collect():
                for sample in metric.samples:
                    labels = sample.labels
                    key = f"{labels['repo']}_{labels['model']}_{labels['engine']}"
                    summary["output_tokens"][key] = sample.value

        except Exception as e:
            logger.error(f"Failed to get metrics summary: {e}")

        return summary
