name: At every commit
on:
  push:
    branches-ignore:
      - main

jobs:
  ruff:
    uses: ./.github/workflows/units/unit_ruff.yml
  python-tests:
    uses: ./.github/workflows/units/unit_python_tests.yml

