name: build_and_push_pretags

on:
  push:
    tags:
      - 'v*-pre*'

env:
  REGISTRY_IMAGE: alessiocasco/automerge

jobs:
  ruff:
    uses: ./.github/workflows/units/unit_ruff.yml
  python-tests:
    uses: ./.github/workflows/units/unit_python_tests.yml
  docker-build-and-push:
    uses: ./.github/workflows/units/unit_build_and_push.yml
    