name: Ruff and unittest
on:
  push:
    branches-ignore:
      - main
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: --ignore E501
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Test with unittest
        run: |
          python3 -m unittest discover -s ./tests  -p 'test_*.py'
