name: Ruff-and-tests
on:
  push:
    branches-ignore:
      - main
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: --ignore E501
  python-tests:
    uses: ./.github/workflows/python_tests.yml

