name: ruff
on:
  workflow_call:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: chartboost/ruff-action@v1
        with:
          args: --ignore E501
          # ruff version while https://github.com/ChartBoost/ruff-action/issues/30 is fixed
          version: 0.4.10
