name: python tests
on:
  workflow_call:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Test with unittest and coverage
        run: |
          coverage run -m unittest discover -s ./tests -p 'test_*.py'
          coverage report
          coverage xml
      - name: Python Coverage Comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
